# Generated by Django 4.1.3 on 2023-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('email', models.EmailField(max_length=254)),
                ('premium', models.BooleanField(default=False)),
                ('used_space', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.EmailField(max_length=254),
        ),
    ]
