# Generated by Django 4.1.3 on 2023-02-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stripesubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriber',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
