# Generated by Django 4.1.3 on 2023-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_stripesubscriber_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriber',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
