# Generated by Django 4.1.3 on 2023-04-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stripesubscriber_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_space',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
