# Generated by Django 4.1.3 on 2023-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_used_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sharable',
            field=models.BooleanField(default=True),
        ),
    ]
